FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt /app

RUN apt-get update && apt-get install -y curl && pip install -r requirements.txt


COPY . /app


EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]